analyzer:
  errors:
    avoid_slow_async_io: ignore
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
