name: version_assist
description: A comprehensive CLI tool for managing version numbers in Flutter/Dart projects, supporting semantic versioning, build numbers, version control integration, and documentation updates.
version: 1.3.4
repository: https://github.com/kuyazee/VersionAssist
homepage: https://github.com/kuyazee/VersionAssist

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  intl: ^0.20.1
  mason_logger: ^0.3.0
  path: ^1.8.0
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

version_gen:
  path: lib/src/

executables:
  version_assist:
